routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function() {
	/*Dashboard*/
	Route::get('/', 'Admin\DhasboardController@index');
	/*Pengamal*/
	Route::resource('/pengamal', 'Admin\PengamalController');
	Route::get('/set-die/{id}/pengamal', 'Admin\PengamalController@setDie')->name('pengamal.set-die');
	Route::get('/set-alive/{id}/pengamal', 'Admin\PengamalController@setAlive')->name('pengamal.set-alive');
	Route::post('/store-die/pengamal/{id}', 'Admin\PengamalController@storeDie')->name('pengamal.store-die');
	Route::post('/store-alive/pengamal/{id}', 'Admin\PengamalController@storeAlive')->name('pengamal.store-alive');

	Route::get('/table/pengamal', 'Admin\PengamalController@dataTable')->name('table.user');
	Route::post('/get-region', 'Admin\PengamalController@getRegion')->name('get.region');
	/*KK*/
	Route::resource('/kk', 'Admin\KkController');
	Route::get('/get-pengaml/kk', 'Admin\KkController@getPengamalList')->name('get.pengamal.list');
	Route::get('/table/kk', 'Admin\KkController@dataTable')->name('table.kk');
	/*Kk Detail*/
	Route::resource('/kk-detail', 'Admin\KkDetailController',['except' => ['create']]);
	Route::get('/kk-detail/create/{kk_detail}', 'Admin\KkDetailController@create')->name('kk-detail.create');
	Route::get('/table/kk-detail', 'Admin\KkDetailController@dataTable')->name('table.kk.detail');
	/*Count Pengamal*/
	Route::resource('/count-pengamal', 'Admin\CountPengamalController', ['except' => ['show']]);
	Route::get('/table/count-pengamal', 'Admin\CountPengamalController@dataTable')->name('table.count.pengamal');

	Route::group(['middleware' => ['super_admin']], function() {
		/*masterdata*/
		Route::group(['prefix' => 'master-data'], function() {
			/*admin*/
			Route::resource('/admin', 'Admin\MasterData\UserAdminController', ['except' => ['show']]);
			Route::get('/table/admin', 'Admin\MasterData\UserAdminController@dataTable')->name('table.admin');
			/*role*/
			Route::resource('/role', 'Admin\MasterData\RoleController', ['except' => ['show']]);
			Route::get('/table/role', 'Admin\MasterData\RoleController@dataTable')->name('table.role');
			/*Age Ranges*/
			Route::resource('/age-range', 'Admin\MasterData\AgeRangeController', ['except' => ['show']]);
			Route::get('/table/age-range', 'Admin\MasterData\AgeRangeController@dataTable')->name('table.age.range');
		});
	});

	/*Logout*/
	Route::post('/logout', 'Admin\AuthController@logout')->name('logout');
});

/*auht*/
Route::get('/login', 'Admin\AuthController@login')->name('login');
Route::post('/process-login', 'Admin\AuthController@processLogin')->name('process.login');

app/Pengamal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pengamal extends Model
{
    protected $guarded = [];
    protected $table = 'pengamal';

    public function kelurahan() {
    	return $this->belongsTo('App\Kelurahan', 'kel_id', 'id');
    }

    public function kecamatan() {
    	return $this->belongsTo('App\Kecamatan', 'kec_id', 'id');
    }

    public function kabupaten() {
    	return $this->belongsTo('App\Kabupaten', 'kab_id', 'id');
    }

    public function provinsi() {
    	return $this->belongsTo('App\Provinsi', 'prov_id', 'id');
    }

    public function job() {
        return $this->belongsTo('App\Job', 'job_id', 'id');
    }

    public function education() {
        return $this->belongsTo('App\Education', 'education_id', 'id');
    }

    public function salary() {
        return $this->belongsTo('App\Salary', 'salary_id', 'id');
    }
}

app/Http/Controllers/Admin/PengamalController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Provinsi;
use App\Kabupaten;
use App\Kecamatan;
use App\Kelurahan;
use App\Pengamal;
use App\Job;
use App\Education;
use App\Salary;
use App\AgeRange;

use GlobalHelper;

use App\Http\Resources\PengamalResource;

use DataTables;
use Faker\Factory as Faker;
use DB;
use Carbon\Carbon;
use File;
use Auth;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class PengamalController extends Controller
{
    public function index()
    {
        $minAge = ['' => 'minimal umur'];
        $maxAge = ['' => 'maksimal umur'];
        for ($i=0; $i < 101; $i++) { 
             $minAge[$i] = $i;
             $maxAge[$i] = $i;
         }

        $filter_location = $this->_getFilterLocation('layouts.component._filter_location');
        // return $filter_location;

        $arr_job = $this->_arrSelect(Job::all()->pluck('job', 'id'), 'Pilih Pekerjaan');
        $arr_edu = $this->_arrSelect(Education::all()->pluck('education', 'id'), 'Pilih Pendidikan');
        $arr_salary = $this->_arrSelect(Salary::all()->pluck('name', 'id'), 'Pilih Penghasilan');
        return view('pengamal.list', compact('arr_job', 'arr_edu', 'minAge', 'maxAge', 'arr_salary', 'filter_location'));
    }

    private function _arrSelect($model, $selected) {
        $arr = ['' => $selected];
        foreach ($model as $key => $value) {
            $arr[$key] = $value;
        }

        return $arr;
    }

    private function _getFilterLocation($path_component, $prov_id = '') {
        $admin = Auth::user();
        $role = config('global.role')[$admin->role];
        $provinsi = Provinsi::where('id', $admin->prov_id)->first();
        $kabupaten = Kabupaten::where('id', $admin->kab_id)->first();
        $kecamatan = Kecamatan::where('id', $admin->kec_id)->first();
        $kelurahan = Kelurahan::where('id', $admin->kel_id)->first();
        $arr_prov = $this->_arrSelect(provinsi::all()->pluck('nama', 'id'), 'Pilih Provinsi');
        return view($path_component, [
            'model' => $admin,
            'role' => $role,
            'arr_prov' => $arr_prov,
            'provinsi' => $provinsi,
            'kabupaten' => $kabupaten,
            'kecamatan' => $kecamatan,
            'kelurahan' => $kelurahan,
            'prov_id' => $prov_id,

        ]);
    }

    public function create()
    {
        $model = New Pengamal;

        $arr_job = $this->_arrSelect(Job::all()->pluck('job', 'id'), 'Pilih Pekerjaan');
        $arr_edu = $this->_arrSelect(Education::all()->pluck('education', 'id'), 'Pilih Pendidikan');
        $arr_salary = $this->_arrSelect(Salary::all()->pluck('name', 'id'), 'Pilih Penghasilan');
        // $arr_prov = $this->_arrSelect(provinsi::all()->pluck('nama', 'id'), 'Pilih Provinsi');
        $form_location = $this->_getFilterLocation('layouts.component._form_location');

        return view('pengamal.form', compact('model', 'arr_job', 'arr_edu','arr_salary', 'form_location'));
    }

    private function _validator($data, $id = '') {
        return  Validator::make($data, [
            // 'address' => 'required',
            'blood' => 'required',
            'birth_date' => 'required',
            'education_id' => 'required',
            'gender' => 'required',
            'job_id' => 'required',
            'kab_id' => 'required',
            'kec_id' => 'required',
            'kel_id' => 'required',
            'married' => 'required',
            'name' => 'required|string',
            'nik' => 'required|numeric|unique:pengamal,nik,'.$id,
            'prov_id' => 'required',
            'ktp_path_send' => 'required',
        ], [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah terdaftar',
            'numeric' => ':attribute harus berupa angka',
        ], [
            // 'address' => 'Alamat',
            'blood' => 'Gol. Darah',
            'birth_date' => 'Tanggal Lahir',
            'education_id' => 'Pendidikan',
            'gender' => 'Jenis Kelamin',
            'job_id' => 'Pekerjaan',
            'prov_id' => 'Provinsi',
            'kab_id' => 'Kabupaten',
            'kec_id' => 'Kecamatan',
            'kel_id' => 'Kelurahan',
            'married' => 'Status',
            'name' => 'Nama',
            'nik' => 'NIK',
            'ktp_path_send' => 'KTP harus di isi',
        ])->validate();
    }


    public function store(Request $request)
    {
        $validated = $this->_validator($request->all());
        $validated['salary_id'] = $request->salary_id;
        unset($validated['ktp_path_send']);

        if($request->upload_ktp) {
            $img_path = GlobalHelper::uploadImage('ktp',$request->upload_ktp);
            $validated['ktp_path'] = $img_path;
        }

        $model = Pengamal::create($validated);
        return $model;
    }

    public function show($id)
    {
        //
    }

    public function setDie($id)
    {
        $model = Pengamal::findOrFail($id);
        return view('pengamal.set_die', compact('model'));
    }

    public function storeDie(Request $request, $id)
    {
        $model = Pengamal::findOrFail($id);
        $data['die_date'] = $request->die_date;
        $data['has_die'] = 1;
        return $model->update($data);
    }

    public function setAlive($id)
    {
        $model = Pengamal::findOrFail($id);
        return view('pengamal.set_alive', compact('model'));
    }

    public function storeAlive(Request $request, $id)
    {
        $model = Pengamal::findOrFail($id);
        $data['has_die'] = $request->has_die;
        $data['die_date'] = null;
        return $model->update($data);
    }

    public function edit($id)
    {
        $model = Pengamal::findOrFail($id);
        $prov_id = $model->prov_id;

        $arr_job = $this->_arrSelect(Job::all()->pluck('job', 'id'), 'Pilih Pekerjaan');
        $arr_edu = $this->_arrSelect(Education::all()->pluck('education', 'id'), 'Pilih Pendidikan');
        $arr_salary = $this->_arrSelect(Salary::all()->pluck('name', 'id'), 'Pilih Penghasilan');

        $form_location = $this->_getFilterLocation('layouts.component._form_location', $prov_id);

        return view('pengamal.form', compact('model', 'arr_job', 'arr_edu','arr_salary', 'form_location'));
    }

    public function update(Request $request, $id)
    {
        $model = Pengamal::findOrFail($id);

        $validated = $this->_validator($request->all(), $id);
        $validated['salary_id'] = $request->salary_id;
        unset($validated['ktp_path_send']);

        if($request->upload_ktp) {
            $path_delete = $model->ktp_path;
            $img_path = GlobalHelper::uploadImage('ktp',$request->upload_ktp, $path_delete);
            $validated['ktp_path'] = $img_path;
        }

        return $model->update($validated);
    }

    public function destroy($id)
    {
        $model = Pengamal::findOrFail($id);
        return $model->delete();
    }

    public function dataTable(Request $request) {
        $model = Pengamal::with(['job', 'education', 'provinsi', 'kabupaten', 'kecamatan', 'kelurahan', 'salary']);

        // return response()->json($request);
        // 
        // return response()->json($request->min_age !== 'x');
        
        if(!empty($request->id_prov)) {
            $model->where('prov_id', $request->id_prov);
        } 

        if(!empty($request->id_kab)) {
            $model->where('kab_id', $request->id_kab);
        } 

        if(!empty($request->id_kec)) {
            $model->where('kec_id', $request->id_kec);
        } 

        if(!empty($request->id_kel)) {
            $model->where('kel_id', $request->id_kel);
        }

        if(!empty($request->education_id)) {
            $model->where('education_id', $request->education_id);
        }

        if(!empty($request->job_id)) {
            $model->where('job_id', $request->job_id);
        }

        if(!empty($request->salary_id)) {
            $model->where('salary_id', $request->salary_id);
        }

        if(!empty($request->gender)) {
            $model->where('gender', $request->gender);
        }

        if(!empty($request->blood)) {
            $model->where('blood', $request->blood);
        }

        if(!empty($request->married)) {
            $model->where('married', $request->married);
        }

        if($request->has_die !== null) {
            $model->where('has_die', $request->has_die);
        }

        if($request->min_age !== null && $request->max_age !== null) {
            // return response()->json('run filter age');
            $min_age = $request->min_age;
            $max_age = $request->max_age;
            $dateRange = GlobalHelper::rangeDateAge($min_age, $max_age);
            $minDate = $dateRange['min-date'];
            $maxDate = $dateRange['max-date'];

            $model->whereBetween('birth_date', [$minDate, $maxDate]);
        }

        if(!empty($request->jamaah)) {
            $age_range = [];
            $gender = '';
            switch ($request->jamaah) {
                case 'Kanak-Kanak':
                    $age_range = AgeRange::where('name', 'Kanak-Kanak')->first();
                    break;
                case 'Remaja':
                    $age_range = AgeRange::where('name', 'Remaja')->first();
                    break;
                case 'Ibu-Ibu':
                    $age_range = AgeRange::where('name', 'Dewasa')->first();
                    $gender = 'Perempuan';
                    break;
                case 'Bapak-Bapak':
                    $gender = 'Laki-Laki';
                    $age_range = AgeRange::where('name', 'Dewasa')->first();
                    break;
                default:
                    break;
            }
            $min_age = $age_range->min_age;
            $max_age = $age_range->max_age;
            $dateRange = GlobalHelper::rangeDateAge($min_age, $max_age);

resources/views/pengamal/list.blade.php
@extends('layouts.master')

@section('title') 
  Pengamal
@endsection

@section('head_title') 
  Pengamal
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">Pengamal</a></li>
@endsection

@section('content')
<div class="container-fluid">
<div class="row">
  <div class="col-12">
    <div class="card collapsed-card">
      <div class="card-header">
        <h3 class="card-title">Filter</h3>

        <div class="card-tools">
          {{-- <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fas fa-times"></i></button> --}}
            <a href="{{route('pengamal.create')}}" class="btn btn-success btn-sm modal-show" title="Tambah Pengamal"><i class="fas fa-plus"></i> Tambah</a>
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fas fa-minus"></i></button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        {{-- Table Field --}}
        <div class="form-group row filter-location">
          {!! $filter_location !!}
        </div>
        <div class="form-group row">
            <div class="col-md-2">
                {!! Form::dropdownRaw('select_gender' , 'Jenis Kelamin' , config('select.gender')) !!}
            </div>
            <div class="col-md-2">
                {!! Form::dropdownRaw('select_blood' , 'Gol. Darah' , config('select.blood')) !!}
            </div>
            <div class="col-md-2">
                {!! Form::dropdownRaw('select_education' , 'Pendidikan' , $arr_edu) !!}
            </div>
            <div class="col-md-3">
                {!! Form::dropdownRaw('select_job' , 'Pekerjaan' , $arr_job) !!}
            </div>
            <div class="col-md-3">
                {!! Form::dropdownRaw('select_salary' , 'Pilih Penghasilan', $arr_salary) !!}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-2">
                {!! Form::dropdownRaw('min_age' , 'Min Age' , $minAge) !!}
            </div>
            <div class="col-md-2">
                {!! Form::dropdownRaw('max_age' , 'Max Age' , $maxAge) !!}
            </div>
            <div class="col-md-2">
                {!! Form::dropdownRaw('jamaah' , 'Jamaah', config('select.jamaah')) !!}
            </div>
            <div class="col-md-2">
                {!! Form::dropdownRaw('select_status' , 'Status' , config('select.married')) !!}
            </div>
            <div class="col-md-2">
                {!! Form::dropdownRaw('select_is_alive' , 'is_alive' , config('select.has_die')) !!}
            </div>
        </div>
      </div>
      <!-- /.card-body -->
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Data</h3>

        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fas fa-minus"></i></button>
          {{-- <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fas fa-times"></i></button> --}}
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        {{-- Table Field --}}
        <table id="datatable" class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>No</th>
              <th>Nama</th>
              <th>NIK</th>
              <th>Jenis Kelamin</th>
              <th>Gol. Darah</th>
              <th>Tanggal Lahir</th>
              <th>Umur</th>
              <th>Pendidikan</th>
              <th>Pekerjaan</th>
              <th>Penghaslian</th>
              <th>Status</th>
              <th>Jamaah</th>
              <th>Provinsi</th>
              <th>Kabupaten / Kota</th>
              <th>Kecamatan</th>
              <th>Desa</th>
              {{-- <th>Alamat</th> --}}
              <th>Status Hidup</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
  </div>
</div>
</div>
@endsection('')


@section('script')
<script>
  var csrf_token = $('meta[name="csrf-token"]').attr('content');
  var table

  var arr_select = ['select_gender',
                    'select_blood',
                    'select_education',
                    'select_job',
                    'select_status',
                    'select_is_alive',
                    'select_salary',
                    'min_age',
                    'max_age',
                    'jamaah']

  var arr_select_2 = ['select_provinsi',
                      'select_kabupaten',
                      'select_kecamatan',
                      'select_kelurahan',
                      'select_gender',
                      'select_blood',
                      'select_education',
                      'select_job',
                      'select_status',
                      'select_is_alive',
                      'select_salary',
                      'min_age',
                      'max_age',
                      'jamaah']

  $(document).ready(function() {
    var select_provinsi = $('select[name="select_provinsi"]')
    var select_kabupaten = $('select[name="select_kabupaten"]')
    var select_kecamatan = $('select[name="select_kecamatan"]')
    var select_kelurahan = $('select[name="select_kelurahan"]')

    arr_select_2.forEach(function (key, value) {
        $('#' + key).select2()
    });

    // getRegion('provinsi');
    
    getRegion('kabupaten', select_provinsi.children("option:selected").val(), select_kabupaten.children("option:selected").val());
    getRegion('kecamatan', select_kabupaten.children("option:selected").val(), select_kecamatan.children("option:selected").val());
    getRegion('kelurahan', select_kecamatan.children("option:selected").val(), select_kelurahan.children("option:selected").val());

    table = $('#datatable').DataTable({
      dom: '<"html5buttons">iBflrtp',
      // responsive: true,
      processing: true,
      serverSide: true,
      // fixedHeader: true,
      "lengthMenu": [ [10, 25, 50, 100, 1000, -1], [10, 25, 50, 100, 1000, "All"] ],
      scrollX: true,
      ajax: {
          "url"  : "{{ route('table.user') }}", 
          "data" : function (d) {
            d.id_prov = select_provinsi.children("option:selected").val();
            d.id_kab = select_kabupaten.children("option:selected").val();
            d.id_kec = select_kecamatan.children("option:selected").val();
            d.id_kel = select_kelurahan.children("option:selected").val();
            d.gender = $('#select_gender').children("option:selected").val();
            d.blood = $('#select_blood').children("option:selected").val();
            d.education_id = $('#select_education').children("option:selected").val();
            d.job_id = $('#select_job').children("option:selected").val();
            d.salary_id = $('#select_salary').children("option:selected").val();
            d.married = $('#select_status').children("option:selected").val();
            d.has_die = $('#select_is_alive').children("option:selected").val();
            d.min_age = $('#min_age').children("option:selected").val();
            d.max_age = $('#max_age').children("option:selected").val();
            d.jamaah = $('#jamaah').children("option:selected").val();
          }
      },
      columns: [
        {data: 'DT_RowIndex', name: 'id'},
        {data: 'name', name: 'name'},
        {data: 'nik', name: 'nik'},
        {data: 'gender', name: 'gender', searchable: 'false'},
        {data: 'blood', name: 'blood', searchable: 'false'},
        {data: 'birth_date', name: 'birth_date'},
        {data: 'DT_RowData.age', name: 'birth_date', searchable: 'false'},
        {data: 'education.education', name: 'education_id', searchable: 'false'},
        {data: 'job.job', name: 'job_id', searchable: 'false'},
        {data: 'salary.name', name: 'salary_id', searchable: 'false'},
        {data: 'married', name: 'married', searchable: 'false'},
        {data: 'DT_RowData.jamaah', name: 'jamaah', searchable: 'false', orderable: 'false'},
        {data: 'provinsi.nama', name: 'prov_id', searchable: 'false'},
        {data: 'kabupaten.nama', name: 'kab_id', searchable: 'false'},
        {data: 'kecamatan.nama', name: 'kec_id', searchable: 'false'},
        {data: 'kelurahan.nama', name: 'kel_id', searchable: 'false'},
        {data: 'DT_RowData.has_die', name: 'has_die', searchable: 'false'},
        {data: 'action', name: 'action'},
      ]
    });

    $(document).on("change", "select[name='select_provinsi']" , function() {
        id_province = $(this).children("option:selected").val();
        select_kabupaten.html('<option value="">pilih Kabupaten</option>')
        select_kecamatan.html('<option value="">pilih Kecamatan</option>')
        select_kelurahan.html('<option value="">pilih Kelurahan</option>')
        getRegion('kabupaten', id_province);
        table.draw();
    });

    $(document).on("change", "select[name='select_kabupaten']" , function() {
        id_kabupaten = $(this).children("option:selected").val();
        select_kecamatan.html('<option value="">pilih Kecamatan</option>')
        select_kelurahan.html('<option value="">pilih Kelurahan</option>')
        getRegion('kecamatan', id_kabupaten);
        table.draw();
    });

    $(document).on("change", "select[name='select_kecamatan']" , function() {
        id_kecamatan = $(this).children("option:selected").val();
        select_kelurahan.html('<option value="">pilih Kelurahan</option>')
        getRegion('kelurahan', id_kecamatan);
        table.draw();
    });

    $(document).on("change", "select[name='select_kelurahan']" , function() {
        table.draw();
    });

    arr_select.forEach(function (key, value) {
        $('#' + key).on('change', function(e) {
          cekAge = checkAge()
          if(cekAge == 0) {return}
          console.log('run tes')
          table.draw();
        })
    });

    function checkAge() {
      console.log('tes cek age')
      var min_age = parseInt($('#min_age').val())
      var max_age = parseInt($('#max_age').val())

      if(max_age < min_age && min_age != null && max_age != null) {
        alert('max age tidak boleh lebih kecil')
        return 0;
      }
    }


    // $('#select_gender').on('change', function(e) {
    //   table.draw();
    // })

    function getRegion($get_by, $region_id, $is_selected = '') {
      $.ajax({
        url: "{{route('get.region')}}",
        method: "POST",
        "data": {
          '_token' : csrf_token,
          'get_by' : $get_by,
          'region_id' : $region_id,
          'is_selected' : $is_selected,
        },
        success: function(res) {
          if($get_by == 'provinsi') {
            select_provinsi.html(res)
          }
          if($get_by == 'kabupaten') {
            select_kabupaten.html(res)
          }
          if($get_by == 'kecamatan') {
            select_kecamatan.html(res)
          }
          if($get_by == 'kelurahan') {
            select_kelurahan.html(res)
          }
        }
      })
    }
  })
  
</script>
@endsection

resources/views/pengamal/set_alive.blade.php
{!! Form::model($model, [
    'route' => ['pengamal.store-alive', $model->id],
    'method' => 'POST',
]) !!}

{!! Form::dropdownRaw('has_die' , 'Set Hidup', ['1' => 'Set Meninggal','0' => 'Set Hidup']) !!}

{!! Form::close() !!}

resources/views/pengamal/set_die.blade.php
{!! Form::model($model, [
    'route' => ['pengamal.store-die', $model->id],
    'method' => 'POST',
]) !!}

{!! Form::textRaw('die_date' , 'Tanggal Meninggal Dunia') !!}

{!! Form::close() !!}

<script>
  $('input[name="die_date"]').daterangepicker({
    locale: {
        format: 'YYYY-MM-DD'
    },
    singleDatePicker: true,
    showDropdowns: true,
    minYear: 1901,
    maxYear: parseInt(moment().format('YYYY'),10)
  }, function(start, end, label) {
    var years = moment().diff(start, 'years');
    // alert("You are " + years + " years old!");
  });
</script>