routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function() {
	/*Dashboard*/
	Route::get('/', 'Admin\DhasboardController@index');
	/*Pengamal*/
	Route::resource('/pengamal', 'Admin\PengamalController');
	Route::get('/set-die/{id}/pengamal', 'Admin\PengamalController@setDie')->name('pengamal.set-die');
	Route::get('/set-alive/{id}/pengamal', 'Admin\PengamalController@setAlive')->name('pengamal.set-alive');
	Route::post('/store-die/pengamal/{id}', 'Admin\PengamalController@storeDie')->name('pengamal.store-die');
	Route::post('/store-alive/pengamal/{id}', 'Admin\PengamalController@storeAlive')->name('pengamal.store-alive');

	Route::get('/table/pengamal', 'Admin\PengamalController@dataTable')->name('table.user');
	Route::post('/get-region', 'Admin\PengamalController@getRegion')->name('get.region');
	/*KK*/
	Route::resource('/kk', 'Admin\KkController');
	Route::get('/get-pengaml/kk', 'Admin\KkController@getPengamalList')->name('get.pengamal.list');
	Route::get('/table/kk', 'Admin\KkController@dataTable')->name('table.kk');
	/*Kk Detail*/
	Route::resource('/kk-detail', 'Admin\KkDetailController',['except' => ['create']]);
	Route::get('/kk-detail/create/{kk_detail}', 'Admin\KkDetailController@create')->name('kk-detail.create');
	Route::get('/table/kk-detail', 'Admin\KkDetailController@dataTable')->name('table.kk.detail');
	/*Count Pengamal*/
	Route::resource('/count-pengamal', 'Admin\CountPengamalController', ['except' => ['show']]);
	Route::get('/table/count-pengamal', 'Admin\CountPengamalController@dataTable')->name('table.count.pengamal');

	Route::group(['middleware' => ['super_admin']], function() {
		/*masterdata*/
		Route::group(['prefix' => 'master-data'], function() {
			/*admin*/
			Route::resource('/admin', 'Admin\MasterData\UserAdminController', ['except' => ['show']]);
			Route::get('/table/admin', 'Admin\MasterData\UserAdminController@dataTable')->name('table.admin');
			/*role*/
			Route::resource('/role', 'Admin\MasterData\RoleController', ['except' => ['show']]);
			Route::get('/table/role', 'Admin\MasterData\RoleController@dataTable')->name('table.role');
			/*Age Ranges*/
			Route::resource('/age-range', 'Admin\MasterData\AgeRangeController', ['except' => ['show']]);
			Route::get('/table/age-range', 'Admin\MasterData\AgeRangeController@dataTable')->name('table.age.range');
		});
	});

	/*Logout*/
	Route::post('/logout', 'Admin\AuthController@logout')->name('logout');
});

/*auht*/
Route::get('/login', 'Admin\AuthController@login')->name('login');
Route::post('/process-login', 'Admin\AuthController@processLogin')->name('process.login');

app/Kk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kk extends Model
{
    protected $guarded = [];
    protected $table = 'kk';

    public function pengamal() {
    	return $this->belongsTo('App\Pengamal', 'id_pengamal', 'id');
    }

    public function kk_detail()
    {
        return $this->hasMany('App\KkDetail', 'id_kk', 'id');
    }
}

app/Http/Controllers/Admin/KkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use DataTables;
use Carbon\Carbon;
use Auth;
use GlobalHelper;

use App\Kk;
use App\Pengamal;
use App\Provinsi;
use App\Kabupaten;
use App\Kecamatan;
use App\Kelurahan;

class KkController extends Controller
{
    public function index()
    {
        $filter_location = $this->_getFilterLocation('layouts.component._filter_location');
        return view('kk.list', compact('filter_location'));
    }

    public function create()
    {
        $model = New Kk;
        return view('kk.form', compact('model'));
    }

    private function _validator($data) {
        return  Validator::make($data, [
            'no_kk' => 'required|numeric|unique:kk,no_kk',
            'id_pengamal' => 'required|unique:kk,id_pengamal',
            'kk_path_send' => 'required',
        ], [
            'required' => ':attribute tidak boleh kosong',
            'id_pengamal.unique' => ':attribute sudah terdaftar sebagai Kepala Keluarga',
            'no_kk.unique' => ':attribute sudah terdaftar',
            'numeric' => ':attribute harus berupa angka',
        ], [
            'id_pengamal' => 'Nama / NIK',
            'no_kk' => 'No. KK',
        ])->validate();
    }

    public function store(Request $request)
    {
        $validated = $this->_validator($request->all());
        unset($validated['kk_path_send']);

        if($request->upload_kk) {
            $img_path = GlobalHelper::uploadImage('kk',$request->upload_kk);
            $validated['kk_path'] = $img_path;
        }

        $model = Kk::create($validated);
        $model->kk_detail()->create([
            'id_kk' => $model->id,
            'id_pengamal' => $model->id_pengamal,
            'user_as' => 'Ayah',
        ]);
        return $model;
    }

    public function show($id)
    {
        $model = Kk::findOrFail($id);
        return view('kk_detail.list', compact('model'));
    }

    public function edit($id)
    {
        $model = Kk::findOrFail($id);
        return view('kk.form', compact('model'));
    }

    private function _validator_update($data, $id) {
        return  Validator::make($data, [
            'no_kk' => 'required|numeric|unique:kk,no_kk,'.$id,
        ], [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute sudah terdaftar',
            'numeric' => ':attribute harus berupa angka',
        ], [
            'no_kk' => 'No. KK',
        ])->validate();
    }

    public function update(Request $request, $id)
    {
        $validated = $this->_validator_update($request->all(), $id);

        $model = Kk::findOrFail($id);

        if($request->upload_kk) {
            $path_delete = $model->kk_path;
            $img_path = GlobalHelper::uploadImage('kk',$request->upload_kk, $path_delete);
            $validated['kk_path'] = $img_path;
        }
        $model->update($validated);
        return $model;
    }

    public function destroy($id)
    {
        $model = Kk::findOrFail($id);
        $model->delete();
    }

    public function dataTable(Request $request) {
        // return response()->json($request);
        // $model = Kk::with(['pengamal'])->get();
        $model = Kk::join('pengamal', 'pengamal.id', '=', 'kk.id_pengamal')
                ->select('kk.no_kk','kk.id as id_kk', 'pengamal.*');

        if(!empty($request->id_prov)) {
            $model->where('pengamal.prov_id', $request->id_prov);
        } 

        if(!empty($request->id_kab)) {
            $model->where('pengamal.kab_id', $request->id_kab);
        } 

        if(!empty($request->id_kec)) {
            $model->where('pengamal.kec_id', $request->id_kec);
        } 

        if(!empty($request->id_kel)) {
            $model->where('pengamal.kel_id', $request->id_kel);
        }

        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('layouts.component._action', [
                    'model' => $model,
                    'title' => $model->name,
                    'url_show' => route('kk.show', $model->id_kk),
                    'url_edit' => route('kk.edit', $model->id_kk),
                    'url_destroy' => route('kk.destroy', $model->id_kk)
                ]);
            })
            ->addIndexColumn()
            ->setRowData([
                'provinsi' => function($model) {
                    return Provinsi::where('id', $model->prov_id)->first()->nama;
                },
                'kabupaten' => function($model) {
                    return Kabupaten::where('id', $model->kab_id)->first()->nama;
                },
                'kecamatan' => function($model) {
                    return Kecamatan::where('id', $model->kec_id)->first()->nama;
                },
                'kelurahan' => function($model) {
                    return Kelurahan::where('id', $model->kel_id)->first()->nama;
                },
            ])
            ->rawColumns(['action'])
            ->make(true);
    }

    public function getPengamalList(Request $request) {
        $limit = 20;
        $query = $request->q;
        $page =  $request->page;
        $start = ($page - 1) * $limit;
        $retVal = array();

        $modal = Pengamal::select('id' , 'name' , 'nik')
                    ->where('name' , 'like','%'.$query.'%')
                    ->orWhere('nik' , 'like' , '%'.$query.'%');
        $jumlah = $modal->count();
        $res = $modal->limit($limit)->offset($start)->get();
        
        $retVal['total_count'] = $jumlah;
        $retVal['incomplete_results'] = false;
        $retVal['items'] = $res;
        return response()->json($retVal);
    }

    private function _getFilterLocation($path_component) {
        $admin = Auth::user();
        $role = config('global.role')[$admin->role];
        $provinsi = Provinsi::where('id', $admin->prov_id)->first();
        $kabupaten = Kabupaten::where('id', $admin->kab_id)->first();
        $kecamatan = Kecamatan::where('id', $admin->kec_id)->first();
        $kelurahan = Kelurahan::where('id', $admin->kel_id)->first();
        $arr_prov = $this->_arrSelect(provinsi::all()->pluck('nama', 'id'), 'Pilih Provinsi');
        return view($path_component, [
            'model' => $admin,
            'role' => $role,
            'arr_prov' => $arr_prov,
            'provinsi' => $provinsi,
            'kabupaten' => $kabupaten,
            'kecamatan' => $kecamatan,
            'kelurahan' => $kelurahan,

        ]);
    }

    private function _arrSelect($model, $selected) {
        $arr = ['' => $selected];
        foreach ($model as $key => $value) {
            $arr[$key] = $value;
        }

        return $arr;
    }
}

resources/views/kk/form.blade.php
{!! Form::model($model, [
    'route' => $model->exists ? ['kk.update', $model->id] : 'kk.store',
    'method' => $model->exists ? 'PUT' : 'POST'
]) !!}

<input type="hidden" name="upload_kk" id="upload_kk" value="">

@if(!$model->exists)
{!! Form::dropdownRaw('id_pengamal' , 'Nama Kepala Keluarga') !!}
@endif
{!! Form::textRaw('no_kk' , 'No. KK') !!}
{!! Form::fileRaw('kk_path' , 'Foto KK : ') !!}
<input type="hidden" name="kk_path_send" id="kk_path_send" value="{{$model->kk_path ? 'exist' : ''}}">
<p>maksimal foto 1 MB</p>
<div id="image-preview"></div>

{!! Form::close() !!}

<script>
	var module_url = "{{route('get.pengamal.list')}}"
    var image_crop = ''
    var reader = ''
    var img_path = "{{$model->kk_path}}"
    var img_model = "{{asset($model->kk_path)}}"

	function formatRepo (repo) {
        if (repo.loading) return repo.text;
        var markups = "<div class='select2-result-repository clearfix'>" +
            "<div class='select2-result-repository__meta'>" +
            "<div class='select2-result-repository__title'>Name: " + repo.name + "</div>"+
            "<div class='select2-result-repository__description'>NIK :" + repo.nik + "</div>"
            +"</div></div>";
        return markups;
    }

    function formatRepoSelection (repo) {
        return repo.name || repo.text;
    }
	$(document).ready(function() {
        console.log(img_path)
        reader = new FileReader();
        image_crop = $('#image-preview').croppie({
          enableExif:true,
          viewport:{
            width:323,
            height:220,
          },
          boundary:{
            width:'100%',
            height:300
          }
        });

        if(img_path !== '') {
          image_crop.croppie('bind', {
            url:img_model
          })
        }

        function cek_img(img) {
          var size_max = 1024 * 1000
          var size_img = img.files[0].size
          var ext = $(img).val().split('.').pop().toLowerCase();
          if ($.inArray(ext, ['gif','png','jpg','jpeg']) == -1) {
            alert('Image Format Harus JPG, JPEG, PNG or GIF.')
            return 0
          } else {
            if(size_img > size_max) {
              alert('File tidak boleh lebih dari 1 Mb')
              return 0
            }
          }
          return 1
        }

        $('#kk_path').change(function(){
          if(cek_img(this) == 0) {
            $('#kk_path').val('');
            return
          } else {
            $('#kk_path_send').val('exist')
          }
          reader.onload = function(event){
            // console.log(event.target.result)
            image_crop.croppie('bind', {
              url:event.target.result
            }).then(function(){
              console.log('jQuery bind complete');
            });
          }
          reader.readAsDataURL(this.files[0]);
        });

        $('#modal-btn-save').on('click', function() {
          image_crop.croppie('result', {
            type:'canvas',
            size:'original'
          }).then(function(response){
            $('#upload_kk').val(response)
          });
        })

		$('#id_pengamal').select2({
            ajax: {
                url: module_url,
                dataType: 'json',
                delay: 250,
                data: function (params) {
                    return {
                    q: params.term, // search term
                    page: params.page,
                    };
                },
                processResults: function (data, params) {
                params.page = params.page || 1;
                return {
                results: data.items,
                pagination: {
                    more: (params.page * 20) < data.total_count
                }
                };
                },
                cache : true,
	        },
	        escapeMarkup: function (markup) { return markup; }, // let our custom formatter work
	        minimumInputLength: 1,
	        templateResult: formatRepo, // omitted for brevity, see the source of this page
	        templateSelection: formatRepoSelection, // omitted for brevity, see the source of this page
	        placeholder: 'Ketikan Nama / NIK',
	        });
	})
</script>

resources/views/kk/list.blade.php
@extends('layouts.master')

@section('title') 
  Kk
@endsection

@section('head_title') 
  KK
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="#">KK</a></li>
@endsection

@section('content')
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Filter</h3>
  
          <div class="card-tools">
            {{-- <a href="{{route('role.create')}}" class="btn btn-success btn-sm modal-show" title="Tambah Role"><i class="fas fa-plus"></i> Tambah</a> --}}
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fas fa-minus"></i></button>
            {{-- <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fas fa-times"></i></button> --}}
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <div class="form-group row filter-location">
            {!! $filter_location !!}
          </div>
        </div>
        <!-- /.card-body -->
      </div>
    </div>
  </div>
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Data</h3>

        <div class="card-tools">
          <a href="{{route('kk.create')}}" class="btn btn-success btn-sm modal-show" title="Tambah Kk"><i class="fas fa-plus"></i> Tambah</a>
          <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fas fa-minus"></i></button>
          {{-- <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fas fa-times"></i></button> --}}
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        {{-- Table Field --}}
        <table id="datatable" class="table table-bordered table-hover">
          <thead>
            <tr>
              <th>No</th>
              <th>Nama Kepala Keluarga</th>
              <th>No. KK</th>
              <th>Provinsi</th>
              <th>Kabupaten / Kota</th>
              <th>Kecamatan</th>
              <th>Kelurahan</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
  </div>
</div>
</div>
@endsection('')


@section('script')
<script>
  var csrf_token = $('meta[name="csrf-token"]').attr('content');
  var table
  var arr_select_2 = ['select_provinsi','select_kabupaten','select_kecamatan','select_kelurahan',]

  var select_provinsi = $('#select_provinsi')
  var select_kabupaten = $('#select_kabupaten')
  var select_kecamatan = $('#select_kecamatan')
  var select_kelurahan = $('#select_kelurahan')

  $(document).ready(function() {
    arr_select_2.forEach(function (key, value) {
        $('#' + key).select2()
    });

    getRegion('kabupaten', select_provinsi.children("option:selected").val(), select_kabupaten.children("option:selected").val());
    getRegion('kecamatan', select_kabupaten.children("option:selected").val(), select_kecamatan.children("option:selected").val());
    getRegion('kelurahan', select_kecamatan.children("option:selected").val(), select_kelurahan.children("option:selected").val());

    table = $('#datatable').DataTable({
        dom: '<"html5buttons">iBflrtp',
        responsive: false,
        processing: true,
        serverSide: true,
        "lengthMenu": [ [10, 25, 50, 100, 1000, -1], [10, 25, 50, 100, 1000, "All"] ],
        scrollX: true,
        ajax: {
          url : "{{ route('table.kk') }}",
          data : function(d) {
            d.id_prov = select_provinsi.children("option:selected").val();
            d.id_kab = select_kabupaten.children("option:selected").val();
            d.id_kec = select_kecamatan.children("option:selected").val();
            d.id_kel = select_kelurahan.children("option:selected").val();
          }
        },
        columns: [
          {data: 'DT_RowIndex', name: 'id'},
          {data: 'name', name: 'pengamal.name'},
          {data: 'no_kk', name: 'no_kk'},
          {data: 'DT_RowData.provinsi', name: 'prov_id', searchable: 'false'},
          {data: 'DT_RowData.kabupaten', name: 'kab_id', searchable: 'false'},
          {data: 'DT_RowData.kecamatan', name: 'kec_id', searchable: 'false'},
          {data: 'DT_RowData.kelurahan', name: 'kel_id', searchable: 'false'},
          {data: 'action', name: 'action'}
        ]
    });

    $(document).on("change", "select[name='select_provinsi']" , function() {
        id_province = $(this).children("option:selected").val();
        select_kabupaten.html('<option value="">pilih Kabupaten</option>')
        select_kecamatan.html('<option value="">pilih Kecamatan</option>')
        select_kelurahan.html('<option value="">pilih Kelurahan</option>')
        getRegion('kabupaten', id_province);
        table.draw();
    });

    $(document).on("change", "select[name='select_kabupaten']" , function() {
        id_kabupaten = $(this).children("option:selected").val();
        select_kecamatan.html('<option value="">pilih Kecamatan</option>')
        select_kelurahan.html('<option value="">pilih Kelurahan</option>')
        getRegion('kecamatan', id_kabupaten);
        table.draw();
    });

    $(document).on("change", "select[name='select_kecamatan']" , function() {
        id_kecamatan = $(this).children("option:selected").val();
        select_kelurahan.html('<option value="">pilih Kelurahan</option>')
        getRegion('kelurahan', id_kecamatan);
        table.draw();
    });

    $(document).on("change", "select[name='select_kelurahan']" , function() {
        table.draw();
    });

    function getRegion($get_by, $region_id, $is_selected = '') {
      $.ajax({
        url: "{{route('get.region')}}",
        method: "POST",
        "data": {
          '_token' : csrf_token,
          'get_by' : $get_by,
          'region_id' : $region_id,
          'is_selected' : $is_selected,
        },
        success: function(res) {
          if($get_by == 'provinsi') {
            select_provinsi.html(res)
          }
          if($get_by == 'kabupaten') {
            select_kabupaten.html(res)
          }
          if($get_by == 'kecamatan') {
            select_kecamatan.html(res)
          }
          if($get_by == 'kelurahan') {
            select_kelurahan.html(res)
          }
        }
      })
    }
  })
  
</script>
@endsection